// tslint:disable
/**
 * Tweetwatch Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefaultError
 */
export interface DefaultError {
    /**
     * 
     * @type {string}
     * @memberof DefaultError
     */
    message: string;
}

export function DefaultErrorFromJSON(json: any): DefaultError {
    return DefaultErrorFromJSONTyped(json, false);
}

export function DefaultErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function DefaultErrorToJSON(value?: DefaultError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}


