// tslint:disable
/**
 * Tweetwatch Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefaultSuccess
 */
export interface DefaultSuccess {
    /**
     * 
     * @type {string}
     * @memberof DefaultSuccess
     */
    message: string;
}

export function DefaultSuccessFromJSON(json: any): DefaultSuccess {
    return DefaultSuccessFromJSONTyped(json, false);
}

export function DefaultSuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultSuccess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function DefaultSuccessToJSON(value?: DefaultSuccess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}


