// tslint:disable
/**
 * Tweetwatch Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tweet
 */
export interface Tweet {
    /**
     * 
     * @type {number}
     * @memberof Tweet
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Tweet
     */
    twitterId: number;
    /**
     * 
     * @type {number}
     * @memberof Tweet
     */
    twitterUserId: number;
    /**
     * 
     * @type {string}
     * @memberof Tweet
     */
    twitterUsername: string;
    /**
     * 
     * @type {string}
     * @memberof Tweet
     */
    fullText: string;
    /**
     * 
     * @type {string}
     * @memberof Tweet
     */
    createdAt: string;
}

export function TweetFromJSON(json: any): Tweet {
    return TweetFromJSONTyped(json, false);
}

export function TweetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tweet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'twitterId': json['twitterId'],
        'twitterUserId': json['twitterUserId'],
        'twitterUsername': json['twitterUsername'],
        'fullText': json['fullText'],
        'createdAt': json['createdAt'],
    };
}

export function TweetToJSON(value?: Tweet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'twitterId': value.twitterId,
        'twitterUserId': value.twitterUserId,
        'twitterUsername': value.twitterUsername,
        'fullText': value.fullText,
        'createdAt': value.createdAt,
    };
}


