// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "github.com/dairlair/twitwatch/pkg/entity"
import mock "github.com/stretchr/testify/mock"

import v1 "github.com/dairlair/twitwatch/pkg/api/v1"

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// AddStream provides a mock function with given fields: _a0
func (_m *Interface) AddStream(_a0 entity.StreamInterface) (int64, error) {
	ret := _m.Called(_a0)

	var r0 int64
	if rf, ok := ret.Get(0).(func(entity.StreamInterface) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.StreamInterface) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddTwit provides a mock function with given fields: twit
func (_m *Interface) AddTwit(twit *v1.Twit) (int64, error) {
	ret := _m.Called(twit)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*v1.Twit) int64); ok {
		r0 = rf(twit)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Twit) error); ok {
		r1 = rf(twit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStreams provides a mock function with given fields:
func (_m *Interface) GetStreams() ([]entity.StreamInterface, error) {
	ret := _m.Called()

	var r0 []entity.StreamInterface
	if rf, ok := ret.Get(0).(func() []entity.StreamInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.StreamInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
