// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// AccountOKCode is the HTTP code returned for type AccountOK
const AccountOKCode int = 200

/*AccountOK Returns info about current user

swagger:response accountOK
*/
type AccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewAccountOK creates AccountOK with default headers values
func NewAccountOK() *AccountOK {

	return &AccountOK{}
}

// WithPayload adds the payload to the account o k response
func (o *AccountOK) WithPayload(payload *models.GeneralResponse) *AccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the account o k response
func (o *AccountOK) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
