// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// CheckStatusOKCode is the HTTP code returned for type CheckStatusOK
const CheckStatusOKCode int = 200

/*CheckStatusOK Status of currently authorized user

swagger:response checkStatusOK
*/
type CheckStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewCheckStatusOK creates CheckStatusOK with default headers values
func NewCheckStatusOK() *CheckStatusOK {

	return &CheckStatusOK{}
}

// WithPayload adds the payload to the check status o k response
func (o *CheckStatusOK) WithPayload(payload *models.User) *CheckStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check status o k response
func (o *CheckStatusOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
