// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// CheckStatusHandlerFunc turns a function with the right signature into a check status handler
type CheckStatusHandlerFunc func(CheckStatusParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckStatusHandlerFunc) Handle(params CheckStatusParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// CheckStatusHandler interface for that can handle valid check status params
type CheckStatusHandler interface {
	Handle(CheckStatusParams, *models.User) middleware.Responder
}

// NewCheckStatus creates a new http.Handler for the check status operation
func NewCheckStatus(ctx *middleware.Context, handler CheckStatusHandler) *CheckStatus {
	return &CheckStatus{Context: ctx, Handler: handler}
}

/*CheckStatus swagger:route GET /status checkStatus

CheckStatus check status API

*/
type CheckStatus struct {
	Context *middleware.Context
	Handler CheckStatusHandler
}

func (o *CheckStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCheckStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
