// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// CreateStreamHandlerFunc turns a function with the right signature into a create stream handler
type CreateStreamHandlerFunc func(CreateStreamParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateStreamHandlerFunc) Handle(params CreateStreamParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// CreateStreamHandler interface for that can handle valid create stream params
type CreateStreamHandler interface {
	Handle(CreateStreamParams, *models.User) middleware.Responder
}

// NewCreateStream creates a new http.Handler for the create stream operation
func NewCreateStream(ctx *middleware.Context, handler CreateStreamHandler) *CreateStream {
	return &CreateStream{Context: ctx, Handler: handler}
}

/*CreateStream swagger:route POST /topics/{topicId}/streams createStream

CreateStream create stream API

*/
type CreateStream struct {
	Context *middleware.Context
	Handler CreateStreamHandler
}

func (o *CreateStream) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateStreamParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
