// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// DeleteTopicHandlerFunc turns a function with the right signature into a delete topic handler
type DeleteTopicHandlerFunc func(DeleteTopicParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTopicHandlerFunc) Handle(params DeleteTopicParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DeleteTopicHandler interface for that can handle valid delete topic params
type DeleteTopicHandler interface {
	Handle(DeleteTopicParams, *models.User) middleware.Responder
}

// NewDeleteTopic creates a new http.Handler for the delete topic operation
func NewDeleteTopic(ctx *middleware.Context, handler DeleteTopicHandler) *DeleteTopic {
	return &DeleteTopic{Context: ctx, Handler: handler}
}

/*DeleteTopic swagger:route DELETE /topics/{topicId} deleteTopic

Delete desired topic by Topic ID

*/
type DeleteTopic struct {
	Context *middleware.Context
	Handler DeleteTopicHandler
}

func (o *DeleteTopic) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTopicParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
