// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// GetUserTopicsOKCode is the HTTP code returned for type GetUserTopicsOK
const GetUserTopicsOKCode int = 200

/*GetUserTopicsOK Returns topics list of current user

swagger:response getUserTopicsOK
*/
type GetUserTopicsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Topic `json:"body,omitempty"`
}

// NewGetUserTopicsOK creates GetUserTopicsOK with default headers values
func NewGetUserTopicsOK() *GetUserTopicsOK {

	return &GetUserTopicsOK{}
}

// WithPayload adds the payload to the get user topics o k response
func (o *GetUserTopicsOK) WithPayload(payload []*models.Topic) *GetUserTopicsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user topics o k response
func (o *GetUserTopicsOK) SetPayload(payload []*models.Topic) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserTopicsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Topic, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
