// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// GetTopicTweetsHandlerFunc turns a function with the right signature into a get topic tweets handler
type GetTopicTweetsHandlerFunc func(GetTopicTweetsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTopicTweetsHandlerFunc) Handle(params GetTopicTweetsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetTopicTweetsHandler interface for that can handle valid get topic tweets params
type GetTopicTweetsHandler interface {
	Handle(GetTopicTweetsParams, *models.User) middleware.Responder
}

// NewGetTopicTweets creates a new http.Handler for the get topic tweets operation
func NewGetTopicTweets(ctx *middleware.Context, handler GetTopicTweetsHandler) *GetTopicTweets {
	return &GetTopicTweets{Context: ctx, Handler: handler}
}

/*GetTopicTweets swagger:route GET /topics/{topicId}/tweets getTopicTweets

Returns list of tweets retrieved for this topic

*/
type GetTopicTweets struct {
	Context *middleware.Context
	Handler GetTopicTweetsHandler
}

func (o *GetTopicTweets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTopicTweetsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
