// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// GetTopicTweetsOKCode is the HTTP code returned for type GetTopicTweetsOK
const GetTopicTweetsOKCode int = 200

/*GetTopicTweetsOK Tweets list

swagger:response getTopicTweetsOK
*/
type GetTopicTweetsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Tweet `json:"body,omitempty"`
}

// NewGetTopicTweetsOK creates GetTopicTweetsOK with default headers values
func NewGetTopicTweetsOK() *GetTopicTweetsOK {

	return &GetTopicTweetsOK{}
}

// WithPayload adds the payload to the get topic tweets o k response
func (o *GetTopicTweetsOK) WithPayload(payload []*models.Tweet) *GetTopicTweetsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get topic tweets o k response
func (o *GetTopicTweetsOK) SetPayload(payload []*models.Tweet) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTopicTweetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Tweet, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetTopicTweetsDefault Error

swagger:response getTopicTweetsDefault
*/
type GetTopicTweetsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.DefaultError `json:"body,omitempty"`
}

// NewGetTopicTweetsDefault creates GetTopicTweetsDefault with default headers values
func NewGetTopicTweetsDefault(code int) *GetTopicTweetsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTopicTweetsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get topic tweets default response
func (o *GetTopicTweetsDefault) WithStatusCode(code int) *GetTopicTweetsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get topic tweets default response
func (o *GetTopicTweetsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get topic tweets default response
func (o *GetTopicTweetsDefault) WithPayload(payload *models.DefaultError) *GetTopicTweetsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get topic tweets default response
func (o *GetTopicTweetsDefault) SetPayload(payload *models.DefaultError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTopicTweetsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
