// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// GetStatusOKCode is the HTTP code returned for type GetStatusOK
const GetStatusOKCode int = 200

/*GetStatusOK Current JWT is valid

swagger:response getStatusOK
*/
type GetStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewGetStatusOK creates GetStatusOK with default headers values
func NewGetStatusOK() *GetStatusOK {

	return &GetStatusOK{}
}

// WithPayload adds the payload to the get status o k response
func (o *GetStatusOK) WithPayload(payload *models.User) *GetStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get status o k response
func (o *GetStatusOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetStatusForbiddenCode is the HTTP code returned for type GetStatusForbidden
const GetStatusForbiddenCode int = 403

/*GetStatusForbidden Invalid JWT

swagger:response getStatusForbidden
*/
type GetStatusForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultError `json:"body,omitempty"`
}

// NewGetStatusForbidden creates GetStatusForbidden with default headers values
func NewGetStatusForbidden() *GetStatusForbidden {

	return &GetStatusForbidden{}
}

// WithPayload adds the payload to the get status forbidden response
func (o *GetStatusForbidden) WithPayload(payload *models.DefaultError) *GetStatusForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get status forbidden response
func (o *GetStatusForbidden) SetPayload(payload *models.DefaultError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStatusForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetStatusDefault Error

swagger:response getStatusDefault
*/
type GetStatusDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.DefaultError `json:"body,omitempty"`
}

// NewGetStatusDefault creates GetStatusDefault with default headers values
func NewGetStatusDefault(code int) *GetStatusDefault {
	if code <= 0 {
		code = 500
	}

	return &GetStatusDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get status default response
func (o *GetStatusDefault) WithStatusCode(code int) *GetStatusDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get status default response
func (o *GetStatusDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get status default response
func (o *GetStatusDefault) WithPayload(payload *models.DefaultError) *GetStatusDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get status default response
func (o *GetStatusDefault) SetPayload(payload *models.DefaultError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStatusDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
