// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// GetUserTopicsHandlerFunc turns a function with the right signature into a get user topics handler
type GetUserTopicsHandlerFunc func(GetUserTopicsParams, *models.UserResponse) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserTopicsHandlerFunc) Handle(params GetUserTopicsParams, principal *models.UserResponse) middleware.Responder {
	return fn(params, principal)
}

// GetUserTopicsHandler interface for that can handle valid get user topics params
type GetUserTopicsHandler interface {
	Handle(GetUserTopicsParams, *models.UserResponse) middleware.Responder
}

// NewGetUserTopics creates a new http.Handler for the get user topics operation
func NewGetUserTopics(ctx *middleware.Context, handler GetUserTopicsHandler) *GetUserTopics {
	return &GetUserTopics{Context: ctx, Handler: handler}
}

/*GetUserTopics swagger:route GET /topics getUserTopics

GetUserTopics get user topics API

*/
type GetUserTopics struct {
	Context *middleware.Context
	Handler GetUserTopicsHandler
}

func (o *GetUserTopics) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserTopicsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserResponse
	if uprinc != nil {
		principal = uprinc.(*models.UserResponse) // this is really a models.UserResponse, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
