// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// GetStreamsHandlerFunc turns a function with the right signature into a get streams handler
type GetStreamsHandlerFunc func(GetStreamsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStreamsHandlerFunc) Handle(params GetStreamsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetStreamsHandler interface for that can handle valid get streams params
type GetStreamsHandler interface {
	Handle(GetStreamsParams, *models.User) middleware.Responder
}

// NewGetStreams creates a new http.Handler for the get streams operation
func NewGetStreams(ctx *middleware.Context, handler GetStreamsHandler) *GetStreams {
	return &GetStreams{Context: ctx, Handler: handler}
}

/*GetStreams swagger:route GET /topics/{topicId}/streams getStreams

Returns list of streams inside the topic

*/
type GetStreams struct {
	Context *middleware.Context
	Handler GetStreamsHandler
}

func (o *GetStreams) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetStreamsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
