// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LoginCORSOKCode is the HTTP code returned for type LoginCORSOK
const LoginCORSOKCode int = 200

/*LoginCORSOK login c o r s o k

swagger:response loginCORSOK
*/
type LoginCORSOK struct {
}

// NewLoginCORSOK creates LoginCORSOK with default headers values
func NewLoginCORSOK() *LoginCORSOK {

	return &LoginCORSOK{}
}

// WriteResponse to the client
func (o *LoginCORSOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
