// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// LoginCORSHandlerFunc turns a function with the right signature into a login c o r s handler
type LoginCORSHandlerFunc func(LoginCORSParams, *models.UserResponse) middleware.Responder

// Handle executing the request and returning a response
func (fn LoginCORSHandlerFunc) Handle(params LoginCORSParams, principal *models.UserResponse) middleware.Responder {
	return fn(params, principal)
}

// LoginCORSHandler interface for that can handle valid login c o r s params
type LoginCORSHandler interface {
	Handle(LoginCORSParams, *models.UserResponse) middleware.Responder
}

// NewLoginCORS creates a new http.Handler for the login c o r s operation
func NewLoginCORS(ctx *middleware.Context, handler LoginCORSHandler) *LoginCORS {
	return &LoginCORS{Context: ctx, Handler: handler}
}

/*LoginCORS swagger:route OPTIONS /login loginCORS

LoginCORS login c o r s API

*/
type LoginCORS struct {
	Context *middleware.Context
	Handler LoginCORSHandler
}

func (o *LoginCORS) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLoginCORSParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserResponse
	if uprinc != nil {
		principal = uprinc.(*models.UserResponse) // this is really a models.UserResponse, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
