// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// SignupOKCode is the HTTP code returned for type SignupOK
const SignupOKCode int = 200

/*SignupOK User created

swagger:response signupOK
*/
type SignupOK struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewSignupOK creates SignupOK with default headers values
func NewSignupOK() *SignupOK {

	return &SignupOK{}
}

// WithPayload adds the payload to the signup o k response
func (o *SignupOK) WithPayload(payload *models.GeneralResponse) *SignupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the signup o k response
func (o *SignupOK) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SignupDefault Error

swagger:response signupDefault
*/
type SignupDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSignupDefault creates SignupDefault with default headers values
func NewSignupDefault(code int) *SignupDefault {
	if code <= 0 {
		code = 500
	}

	return &SignupDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the signup default response
func (o *SignupDefault) WithStatusCode(code int) *SignupDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the signup default response
func (o *SignupDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the signup default response
func (o *SignupDefault) WithPayload(payload *models.ErrorResponse) *SignupDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the signup default response
func (o *SignupDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignupDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
