// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dairlair/tweetwatch/pkg/api/models"
)

// NewUpdateTopicParams creates a new UpdateTopicParams object
// no default values defined in spec.
func NewUpdateTopicParams() UpdateTopicParams {

	return UpdateTopicParams{}
}

// UpdateTopicParams contains all the bound params for the update topic operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateTopic
type UpdateTopicParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Updated topic data
	  Required: true
	  In: body
	*/
	Topic *models.CreateTopicRequest
	/*Numeric ID of the topic to update
	  Required: true
	  In: path
	*/
	TopicID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateTopicParams() beforehand.
func (o *UpdateTopicParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CreateTopicRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("topic", "body"))
			} else {
				res = append(res, errors.NewParseError("topic", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Topic = &body
			}
		}
	} else {
		res = append(res, errors.Required("topic", "body"))
	}
	rTopicID, rhkTopicID, _ := route.Params.GetOK("topicId")
	if err := o.bindTopicID(rTopicID, rhkTopicID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTopicID binds and validates parameter TopicID from path.
func (o *UpdateTopicParams) bindTopicID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("topicId", "path", "int64", raw)
	}
	o.TopicID = value

	return nil
}
