// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LoginUserInputError login user input error
// swagger:model LoginUserInputError
type LoginUserInputError struct {

	// code
	// Required: true
	// Enum: [INVALID_CREDENTIALS]
	Code *string `json:"code"`
}

// Validate validates this login user input error
func (m *LoginUserInputError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var loginUserInputErrorTypeCodePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["INVALID_CREDENTIALS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		loginUserInputErrorTypeCodePropEnum = append(loginUserInputErrorTypeCodePropEnum, v)
	}
}

const (

	// LoginUserInputErrorCodeINVALIDCREDENTIALS captures enum value "INVALID_CREDENTIALS"
	LoginUserInputErrorCodeINVALIDCREDENTIALS string = "INVALID_CREDENTIALS"
)

// prop value enum
func (m *LoginUserInputError) validateCodeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, loginUserInputErrorTypeCodePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *LoginUserInputError) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", m.Code); err != nil {
		return err
	}

	// value enum
	if err := m.validateCodeEnum("code", "body", *m.Code); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LoginUserInputError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoginUserInputError) UnmarshalBinary(b []byte) error {
	var res LoginUserInputError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
